### ISSUE TITLE
US-6 Fjern ordrer/rediger

### ISSUE THREAD

**Issue by ChristianStennicke** [TobiasTheDanish/SemesterOpgave#18]
Som kunde kan jeg fjerne en ordre fra min ordreliste eller kunne redigere min ordre (mål, størrelse osv.).
**Acceptkriterier: Givet at kunden har oprettet en ordre, så skal kunden også have muligheden for at fjerne/redigere ordren igen. Dette skal kun være muligt så længe ordren har den indledende status. Når ordrestatussen ændres til “behandles”, så skal det ikke længere være muligt at fjerne/redigere sin ordre via hjemmesiden. Så skal der derimod henvises til et telefonnummer/mailadresse, man kan kontakte.**
**Vigtighed: Need to have**
**Estimat: Medium**

**Comment by TobiasTheDanish** [comment]
Er vi færdige med denne user story? I så fald, kan vi så ikke bare lukke issue'et?
